### ISSUE TITLE
Won't run on Yosemite

### ISSUE THREAD

**Issue by sibson** [giuseppesalvo/RedisManager#2]
Not sure if El Capitan is a hard requirement or simply a default compile setting?

![screen shot 2016-02-17 at 1 01 21 pm](https://cloud.githubusercontent.com/assets/125162/13124735/a8a15d8e-d576-11e5-8572-303e8be0cf0a.png)

**Comment by giuseppesalvo** [comment]
Hi, it's not a requirement, just a compile setting. Try to rebuild the app with 10.10 and edited info.plist
